[client]
showSidebarNavigation = false

[theme]
base = "dark"
primaryColor = "#E50914"
backgroundColor = "#141414"
secondaryBackgroundColor = "#1F1F1F"
textColor = "#E5E5E5"
font = "sans serif"

[server]
runOnSave = true